### ISSUE TITLE
Failed to load a language-wake package grammar

### ISSUE THREAD

**Issue by terpstra** [sifive/atom-language-wake#1]
1. Click on install
2. See error

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [language-wake](https://github.com/sifive/atom-language-wake) package 0.1.2

### Stack Trace

Failed to load a language-wake package grammar

```
At Cannot find module './build/Release/tree_sitter_wake_binding' in /Users/terpstra/.atom/packages/language-wake/grammars/tree-sitter-wake.cson

Error: Cannot find module './build/Release/tree_sitter_wake_binding'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/language-wake/node_modules/tree-sitter-wake/index.js:2:20)
    at /packages/language-wake/node_modules/tree-sitter-wake/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3144259)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359945)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359786)
    at u (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:580454)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581691
    at FSReqWrap.oncomplete (fs.js:154:21)
  at /packages/language-wake/grammars/tree-sitter-wake.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
language-wake 0.1.2 
```

**Comment by terpstra** [comment]
I managed to get it to work by changing /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh to call python2.7 instead of python.

**Comment by drom** [comment]
wow. how can I fix it for everybody to work?

**Comment by terpstra** [comment]
I don't know. gyp needs to run with python < 3. Is there some way you could modify the bin/install.js to pick an older python?
